services:
  backend:
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
    depends_on:
      - postgres
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=TEST

  postgres:
    image: "postgres:17-alpine"
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
